server:
  port: 8080

spring:
  application:
    name: api-gateway

gateway:
  services:
    veiculos-url: http://localhost:8081
    leilao-url: http://localhost:8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
